name: Windows-Release
permissions:
    contents: write
    pull-requests: read

# Controls when the action will run.
on:
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2022
            is-release:      1
          - os:              windows-2025
            is-release:      1

    env:
      TAG_NAME: '${{ github.ref_name }}'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd #v8.0.0
        with:
          script: |
            const git_sha = context.sha.substring(0, 7)
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('SHORT_SHA', git_sha);

      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install CMake
        uses: lukka/get-cmake@2ecc21724e5215b0e567bc399a2602d2ecb48541 #v4.1.1

      - name: Build it
        run: script/build.ps1

      - name: Package it
        run: script/package.ps1

      - name: Upload the artifacts
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
